title: "ZienthOS"
description: "Custom Android ROM Based On crDroidAndroid"
url: "https://zienthos.github.io"
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
navigation:
  - title: Home
    url: /
  - title: Features
    url: /features/
  - title: Team
    url: /team/
  - title: Devices
    url: /devices/
